services:
  baserow:
    image: baserow/baserow:1.30.1
    environment:
      BASEROW_PUBLIC_URL: 'https://baserow.selfhostyour.tech'
    env_file: ./.env
    networks:
      - internal
      - traefik-public
    volumes:
      - ./data/baserow:/baserow/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.baserow.rule=Host(`baserow.selfhostyour.tech`)
      - traefik.http.routers.baserow.entrypoints=web
      - traefik.http.routers.baserow.middlewares=redirect-to-https
      - traefik.http.routers.baserow-secure.rule=Host(`baserow.selfhostyour.tech`)
      - traefik.http.routers.baserow-secure.entrypoints=websecure
      - traefik.http.routers.baserow-secure.tls=true
      - traefik.http.routers.baserow-secure.tls.certresolver=letsencrypt
      - traefik.http.services.baserow.loadbalancer.server.port=80
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
networks:
  internal:
    driver: bridge
  traefik-public:
    external: true