services:
  gitea_database:
    image: postgres:13.4-alpine
    env_file:
     - ./.env
    environment:
      - POSTGRES_USER=${GITEA_POSTGRES_USER}
      - POSTGRES_PASSWORD=${GITEA_POSTGRES_PASSWORD}
      - POSTGRES_DB=${GITEA_POSTGRES_DB}
    volumes:
      - gitea_database:/var/lib/postgresql/data
    networks:
      - internal
    restart: always

  gitea:
    # Use the latest stable release from https://github.com/go-gitea/gitea/releases
    image: gitea/gitea:1.24.3
    env_file:
     - ./.env
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_database:5432
      - GITEA__database__NAME=${GITEA_POSTGRES_DB}
      - GITEA__database__USER=${GITEA_POSTGRES_USER}
      - GITEA__database__PASSWD=${GITEA_POSTGRES_PASSWORD}
      - GITEA__server__DOMAIN=gitea.${BASE_DOMAIN}
      - GITEA__server__SSH_DOMAIN=gitea.${BASE_DOMAIN}
      - GITEA__server__ROOT_URL=https://gitea.${BASE_DOMAIN}
      - GITEA__server__PROTOCOL=http
      - GITEA__server__HTTP_PORT=3000
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
      - traefik-public
    labels:
      - traefik.enable=${ENABLE_TRAEFIK:-false}
      - traefik.docker.network=traefik-public
      - traefik.http.routers.gitea.rule=Host(`gitea.${BASE_DOMAIN}`)
      - traefik.http.routers.gitea.entrypoints=web
      - "${HTTPS_MIDDLEWARE:+traefik.http.routers.gitea.middlewares=${HTTPS_MIDDLEWARE}}"
      - traefik.http.routers.gitea-secure.rule=Host(`gitea.${BASE_DOMAIN}`)
      - traefik.http.routers.gitea-secure.entrypoints=${HTTPS_ENTRYPOINT:-}
      - traefik.http.routers.gitea-secure.tls=${ENABLE_TLS:-}
      - traefik.http.routers.gitea-secure.tls.certresolver=${TLS_RESOLVER:-}
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - "${REDIRECT_SCHEME:+traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=${REDIRECT_SCHEME}}"
      - "${REDIRECT_PERMANENT:+traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=${REDIRECT_PERMANENT}}"
    restart: always
    depends_on:
      - gitea_database

volumes:
  gitea_database:
  gitea_data:

networks:
  internal:
  traefik-public:
    external: ${ENABLE_TRAEFIK:-false}
    name: ${TRAEFIK_NETWORK:-traefik-public}
